config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "trainings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excercise.rb
class Excercise < ApplicationRecord
end

app/models/training.rb
class Training < ApplicationRecord
  mount_uploader :cover, ImageUploader
  has_many :training_lines, inverse_of: :training
  accepts_nested_attributes_for :training_lines, reject_if: :all_blank, allow_destroy: true
end

app/models/training_line.rb
class TrainingLine < ApplicationRecord
  belongs_to :training
  belongs_to :excercise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @excercises = Excercise.all
  end

  # GET /trainings/1/edit
  def edit
    @excercises = Excercise.all
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:description, :cover, training_lines_attributes: [:id, :excercise_id, :reps, :series, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true) do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <h3>Excercises</h3>

  <div id="training_lines">
    <%= form.fields_for :training_lines do |training_line| %>
    <%= render 'training_line_fields', f: training_line %>
    <% end %>
  </div>

  <div class="links">
    <%= link_to_add_association 'add line', form, :training_lines %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainings/_training_line_fields.erb
<div class="nested-fields">


  <div class="field">
    <%= f.label :excercise %>
    <%= f.select :excercise_id, @excercises.collect {|p| [p.name, p.id] } %>
  </div>

  <div class="field">
    <%= f.label :reps %>
    <%= f.text_field :reps %>
  </div>

  <div class="field">
    <%= f.label :series %>
    <%= f.text_field :series %>
  </div>

  <%= link_to_remove_association "remove line", f %>

</div>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainings</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.description %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @training.description %>
</p>

<p>
  <strong>Cover:</strong>
  <%= image_tag(@training.cover_url) if @training.cover? %>
</p>

<h3>Training lines</h3>

<table>
  <thead>
  <tr>
    <th>Seq</th>
    <th>Excercise</th>
    <th>Reps</th>
    <th>Series</th>
  </tr>
  </thead>

  <tbody>
  <% @training.training_lines.each_with_index do |line, index| %>
    <tr>
      <td><em><%= index + 1 %></em></td>
      <td><%= line.excercise.name %></td>
      <td><%= line.reps %></td>
      <td><%= line.series %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>